### ISSUE TITLE
OAuth를 통해 접근 권한을 가져온다

### ISSUE THREAD

**Issue by yuseon-lim** [devyuseon/image-hosting-helper#2]
- 참고 문서
  - https://developer.chrome.com/docs/extensions/how-to/integrate/oauth?hl=ko

**Comment by yuseon-lim** [comment]
@LuizyHub
공유해준 api key 내 로컬 확장프로그램 등록시 적용 안됨. 확인 부탁합니다~

**Comment by yuseon-lim** [comment]
key 문제는 이 이슈로 #3

**Comment by LuizyHub** [comment]
merge close
